"use client";

import { FormEvent, useRef, useState } from "react";

export function CandidateForm() {
  const formRef = useRef<HTMLFormElement>(null); const [status, setStatus] = useState<"idle"|"sending"|"success"|"error">("idle"); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("sending"); const response = await fetch("/api/candidatos", { method: "POST", body: new FormData(event.currentTarget) }); const data = await response.json().catch(() => ({})); if (response.ok) { setStatus("success"); setMessage("Currículo recebido! A Selecta poderá entrar em contato quando houver uma oportunidade compatível."); formRef.current?.reset(); } else { setStatus("error"); setMessage(data.error ?? "Não foi possível enviar. Tente novamente."); } }
  return <form ref={formRef} className="form-card" onSubmit={submit}><div className="form-grid"><div className="hp-field" aria-hidden="true"><label htmlFor="website">Não preencha este campo</label><input id="website" name="website" tabIndex={-1} autoComplete="off" /></div><div className="field"><label htmlFor="nome">Nome completo *</label><input className="input" id="nome" name="nome" required /></div><div className="field"><label htmlFor="whatsapp">WhatsApp *</label><input className="input" id="whatsapp" name="whatsapp" inputMode="tel" placeholder="(64) 99999-9999" required /></div><div className="field"><label htmlFor="email">E-mail *</label><input className="input" type="email" id="email" name="email" required /></div><div className="field"><label htmlFor="cidade">Cidade *</label><input className="input" id="cidade" name="cidade" defaultValue="Rio Verde - GO" required /></div><div className="field field--full"><label htmlFor="area">Área ou cargo de interesse *</label><input className="input" id="area" name="area" placeholder="Ex.: Administrativo, vendas, logística" required /></div><div className="field field--full"><label htmlFor="experiencia">Resumo da experiência</label><textarea className="textarea" id="experiencia" name="experiencia" placeholder="Conte brevemente suas principais experiências e habilidades" /></div><div className="field field--full"><label htmlFor="curriculo">Currículo em PDF, DOC ou DOCX (máx. 5 MB) *</label><input className="input" type="file" id="curriculo" name="curriculo" accept=".pdf,.doc,.docx" required /></div><label className="field--full form-note"><input type="checkbox" name="consentimento" required /> Autorizo a Selecta a utilizar meus dados para processos seletivos, conforme a Política de Privacidade.</label><div className="field--full">{status === "success" || status === "error" ? <p className={`status-message ${status === "error" ? "status-message--error" : ""}`}>{message}</p> : null}<button className="button" type="submit" disabled={status === "sending"}>{status === "sending" ? "Enviando..." : "Enviar currículo →"}</button></div></div></form>;
}
