import type { Metadata } from "next";
import { InstagramIcon, WhatsAppIcon } from "@/components/social-icons";

export const metadata: Metadata = { title: "Contato", description: "Entre em contato com a Selecta Agência de Empregos." };
export default function ContactPage() {
  const candidateMessage = encodeURIComponent("Olá, gostaria de informações sobre as vagas da Selecta.");
  const companyMessage = encodeURIComponent("Olá, preciso contratar profissionais para minha empresa.");
  return <main id="conteudo" className="page-main"><section className="page-hero"><div className="container"><p className="eyebrow">Contato</p><h1>Vamos conversar sobre o seu próximo passo?</h1><p>Escolha o canal mais conveniente. O atendimento da Selecta é direcionado a candidatos e empresas de Rio Verde - GO.</p></div></section><section className="section"><div className="container contact-grid"><div className="contact-card"><p className="eyebrow">Canais de atendimento</p><h2>Fale diretamente com a Selecta.</h2><div className="contact-list"><div className="contact-item"><b><WhatsAppIcon className="contact-svg" /></b><a href="https://wa.me/5564996133525" target="_blank" rel="noreferrer"><strong>WhatsApp</strong><br />(64) 99613-3525</a></div><div className="contact-item"><b><InstagramIcon className="contact-svg" /></b><a href="https://www.instagram.com/selecta.rv/" target="_blank" rel="noreferrer"><strong>Instagram</strong><br />@selecta.rv</a></div><div className="contact-item"><b>@</b><a href="mailto:selecta.agenciarv@gmail.com"><strong>E-mail</strong><br />selecta.agenciarv@gmail.com</a></div><div className="contact-item"><b>⌖</b><span><strong>Área de atuação</strong><br />Rio Verde - GO</span></div></div></div><div className="form-card"><p className="eyebrow">Atendimento direcionado</p><h2>Como podemos ajudar?</h2><p className="form-note">Escolha uma opção para iniciar a conversa pelo WhatsApp com uma mensagem já preparada.</p><div className="value-stack"><div className="value-item"><b>01</b><div><h3>Estou procurando emprego</h3><p>Quero tirar dúvidas sobre vagas ou candidatura.</p><a className="text-link" href={`https://wa.me/5564996133525?text=${candidateMessage}`} target="_blank" rel="noreferrer">Iniciar conversa →</a></div></div><div className="value-item"><b>02</b><div><h3>Quero contratar</h3><p>Preciso divulgar uma vaga ou iniciar um processo seletivo.</p><a className="text-link" href={`https://wa.me/5564996133525?text=${companyMessage}`} target="_blank" rel="noreferrer">Solicitar atendimento →</a></div></div></div></div></div></section></main>;
}
